// Generated by Wrangler on Fri Aug 16 2024 02:17:20 GMT+0700 (Indochina Time)
// by running `wrangler types`

interface Env {
	DISCORD_APPLICATION_ID: string;
	DISCORD_PUBLIC_KEY: string;
	DISCORD_TOKEN: string;
	DISCORD_GUILD_ID: string;
}
