import { Env as Environment } from 'hono';
import { API } from '@discordjs/core/http-only';
import { WorkerEntrypoint } from 'cloudflare:workers';

interface Myself extends WorkerEntrypoint {
	niceFunction: (arg: any) => Promise<any>;
}
// Generated by Wrangler on Fri Aug 16 2024 14:45:47 GMT+0700 (Indochina Time)
// by running `wrangler types`

interface Env {
	KV_STORE: KVNamespace;
	DISCORD_APPLICATION_OWNER_ID: string;
	DISCORD_APPLICATION_ID: string;
	DISCORD_PUBLIC_KEY: string;
	DISCORD_TOKEN: string;
	DISCORD_GUILD_ID: string;
}

export default interface E extends Environment {
	Bindings: Env;
	Variables: {
		api: API;
	};
}
